spring:
  application:
    name: notification
  config:
    import: optional:configserver:http://localhost:8888/
  profiles:
    active: dev
  mvc:
    apiversion:
      use:
        path-segment: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true